import type { WasteReport } from './types';

export const wasteReports: WasteReport[] = [
  {
    id: 'WR001',
    farmerName: 'John Doe',
    cropType: 'Wheat',
    quantity: 10,
    location: 'Farmdale, Central District',
    status: 'Completed',
    collectionAgent: 'EcoHaul Inc.',
    reportedAt: new Date('2023-10-01T08:00:00Z'),
    lastUpdate: new Date('2023-10-03T14:00:00Z'),
    payment: 200,
    paymentStatus: 'Paid',
  },
  {
    id: 'WR002',
    farmerName: 'Jane Smith',
    cropType: 'Corn',
    quantity: 15,
    location: 'Green Valley, North Province',
    status: 'Processing',
    collectionAgent: 'GreenPickups',
    reportedAt: new Date('2023-10-05T10:30:00Z'),
    lastUpdate: new Date('2023-10-07T11:00:00Z'),
    payment: 300,
    paymentStatus: 'Pending',
  },
  {
    id: 'WR003',
    farmerName: 'Samuel Green',
    cropType: 'Rice',
    quantity: 8,
    location: 'Riverbend, East County',
    status: 'In-Transit',
    collectionAgent: 'EcoHaul Inc.',
    reportedAt: new Date('2023-10-08T09:15:00Z'),
    lastUpdate: new Date('2023-10-09T05:00:00Z'),
    payment: 160,
    paymentStatus: 'Pending',
  },
  {
    id: 'WR004',
    farmerName: 'Emily White',
    cropType: 'Sugarcane',
    quantity: 25,
    location: 'Sugarlands, South Region',
    status: 'Collected',
    collectionAgent: 'AgriCollect',
    reportedAt: new Date('2023-10-10T11:00:00Z'),
    lastUpdate: new Date('2023-10-11T13:20:00Z'),
    payment: 500,
    paymentStatus: 'Pending',
  },
  {
    id: 'WR005',
    farmerName: 'Michael Brown',
    cropType: 'Wheat',
    quantity: 12,
    location: 'Westwood Farms, West Province',
    status: 'Reported',
    collectionAgent: 'N/A',
    reportedAt: new Date('2023-10-12T14:00:00Z'),
    lastUpdate: new Date('2023-10-12T14:00:00Z'),
    payment: 240,
    paymentStatus: 'Pending',
  },
  {
    id: 'WR006',
    farmerName: 'John Doe',
    cropType: 'Corn',
    quantity: 20,
    location: 'Farmdale, Central District',
    status: 'Processing',
    collectionAgent: 'GreenPickups',
    reportedAt: new Date('2023-09-15T09:00:00Z'),
    lastUpdate: new Date('2023-09-18T16:00:00Z'),
    payment: 400,
    paymentStatus: 'Paid',
  },
  {
    id: 'WR007',
    farmerName: 'Patricia Garcia',
    cropType: 'Cotton',
    quantity: 18,
    location: 'Cottonwood, East County',
    status: 'Completed',
    collectionAgent: 'AgriCollect',
    reportedAt: new Date('2023-09-20T13:45:00Z'),
    lastUpdate: new Date('2023-09-23T10:00:00Z'),
    payment: 360,
    paymentStatus: 'Paid',
  },
  {
    id: 'WR008',
    farmerName: 'Samuel Green',
    cropType: 'Sugarcane',
    quantity: 30,
    location: 'Riverbend, East County',
    status: 'Reported',
    collectionAgent: 'N/A',
    reportedAt: new Date('2023-10-13T10:00:00Z'),
    lastUpdate: new Date('2023-10-13T10:00:00Z'),
    payment: 600,
    paymentStatus: 'Pending',
  },
];
